name, stu, chinese, cs, pd = input(), input(), input(), input(), input()
print("Name:" + name)
print("ID:" + stu)
print("Average:" + str((int(chinese)+int(cs)+int(pd))/3))
print("Total:" + str(int(chinese)+int(cs)+int(pd)))